from __future__ import annotations

import base64
import binascii
import json
import re
from dataclasses import dataclass
from datetime import datetime, timedelta
from decimal import Decimal, InvalidOperation
from typing import Any
from zoneinfo import ZoneInfo

import httpx

from tg_agent.services.history import ChatMessage
from tg_agent.services.search import SearchResponse


class OpenRouterError(RuntimeError):
    """Raised when OpenRouter cannot return a usable answer."""


@dataclass(frozen=True, slots=True)
class GeneratedImage:
    """Image generated by OpenRouter."""

    content: bytes
    extension: str


@dataclass(frozen=True, slots=True)
class GeneratedSpeech:
    """Speech audio generated by OpenRouter."""

    content: bytes
    extension: str


@dataclass(frozen=True, slots=True)
class InvoiceIntent:
    """User intent to create a Crypto Pay invoice."""

    amount_usd: Decimal
    accepted_assets: tuple[str, ...]
    description: str


@dataclass(frozen=True, slots=True)
class CalendarEventIntent:
    """User intent to create a Google Calendar event."""

    summary: str
    start_at: datetime
    end_at: datetime
    description: str | None


@dataclass(frozen=True, slots=True)
class OpenRouterClient:
    """Minimal async client for OpenRouter chat completions."""

    api_key: str
    model: str
    image_model: str
    stt_model: str
    tts_model: str
    tts_voice: str
    base_url: str = "https://openrouter.ai/api/v1/chat/completions"
    speech_url: str = "https://openrouter.ai/api/v1/audio/speech"
    app_title: str = "tg-agent"

    async def answer(self, history: list[ChatMessage]) -> str:
        """Return assistant answer using recent chat history."""
        payload = {
            "model": self.model,
            "messages": [
                {
                    "role": "system",
                    "content": (
                        "Ты дружелюбный Telegram-ассистент. Отвечай кратко, "
                        "живым языком и с уместными эмодзи. Делай ответ удобным "
                        "для чата: короткие абзацы, списки с эмодзи-маркерами, "
                        "без тяжелого Markdown и HTML."
                    ),
                },
                *[
                    {"role": message.role, "content": message.content}
                    for message in history
                ],
            ],
        }
        headers = {
            "Authorization": f"Bearer {self.api_key}",
            "Content-Type": "application/json",
            "X-OpenRouter-Title": self.app_title,
        }

        async with httpx.AsyncClient(timeout=30) as client:
            response = await client.post(self.base_url, json=payload, headers=headers)

        if response.status_code >= 400:
            raise OpenRouterError(
                f"OpenRouter request failed with status {response.status_code}."
            )

        return self._extract_content(response.json())

    async def generate_image(self, prompt: str) -> GeneratedImage:
        """Generate an image from a text prompt."""
        payload = {
            "model": self.image_model,
            "messages": [{"role": "user", "content": prompt}],
            "modalities": ["image", "text"],
        }
        headers = {
            "Authorization": f"Bearer {self.api_key}",
            "Content-Type": "application/json",
            "X-OpenRouter-Title": self.app_title,
        }

        async with httpx.AsyncClient(timeout=120) as client:
            response = await client.post(self.base_url, json=payload, headers=headers)

        if response.status_code >= 400:
            raise OpenRouterError(
                f"OpenRouter image request failed with status {response.status_code}."
            )

        image_url = self._extract_image_url(response.json())
        return self._decode_data_url(image_url)

    async def transcribe_audio(self, audio: bytes, audio_format: str) -> str:
        """Transcribe audio bytes without local format conversion."""
        audio_data = base64.b64encode(audio).decode("utf-8")
        payload = {
            "model": self.stt_model,
            "messages": [
                {
                    "role": "user",
                    "content": [
                        {
                            "type": "text",
                            "text": "Расшифруй это аудио. Верни только текст.",
                        },
                        {
                            "type": "input_audio",
                            "input_audio": {
                                "data": audio_data,
                                "format": audio_format,
                            },
                        },
                    ],
                }
            ],
        }
        headers = {
            "Authorization": f"Bearer {self.api_key}",
            "Content-Type": "application/json",
            "X-OpenRouter-Title": self.app_title,
        }

        async with httpx.AsyncClient(timeout=60) as client:
            response = await client.post(self.base_url, json=payload, headers=headers)

        if response.status_code >= 400:
            msg = (
                f"OpenRouter STT request failed with status {response.status_code}: "
                f"{response.text[:500]}"
            )
            raise OpenRouterError(msg)

        return self._extract_content(response.json())

    async def synthesize_speech(self, text: str) -> GeneratedSpeech:
        """Synthesize speech into MP3 bytes without local conversion."""
        payload = {
            "model": self.tts_model,
            "input": text,
            "voice": self.tts_voice,
            "response_format": "mp3",
        }
        headers = {
            "Authorization": f"Bearer {self.api_key}",
            "Content-Type": "application/json",
            "X-OpenRouter-Title": self.app_title,
        }

        async with httpx.AsyncClient(timeout=120) as client:
            response = await client.post(self.speech_url, json=payload, headers=headers)

        if response.status_code >= 400:
            msg = f"OpenRouter TTS request failed with status {response.status_code}."
            raise OpenRouterError(msg)

        return GeneratedSpeech(content=response.content, extension="mp3")

    async def detect_invoice_intent(self, text: str) -> InvoiceIntent | None:
        """Detect whether user asks to create a Crypto Pay invoice."""
        payload = {
            "model": self.model,
            "messages": [
                {
                    "role": "system",
                    "content": (
                        "Ты классификатор намерений для Telegram-бота. "
                        "Определи, хочет ли пользователь создать счет через "
                        "Crypto Pay. Верни только JSON без Markdown. Формат: "
                        '{"create_invoice": boolean, "amount_usd": string|null, '
                        '"assets": string[], "description": string|null}. '
                        "Поддержанные assets: USDT, TON, BTC. Если валюта "
                        "оплаты не указана, верни все три assets. Если сумма "
                        "указана в долларах или со знаком $, amount_usd — это "
                        "число в USD. Если намерения создать счет нет или суммы "
                        "нет, create_invoice=false."
                    ),
                },
                {"role": "user", "content": text},
            ],
        }
        headers = {
            "Authorization": f"Bearer {self.api_key}",
            "Content-Type": "application/json",
            "X-OpenRouter-Title": self.app_title,
        }

        async with httpx.AsyncClient(timeout=30) as client:
            response = await client.post(self.base_url, json=payload, headers=headers)

        if response.status_code >= 400:
            raise OpenRouterError(
                f"OpenRouter intent request failed with status {response.status_code}."
            )

        content = self._extract_content(response.json())
        return self._parse_invoice_intent(content)

    async def detect_calendar_event_intent(
        self,
        text: str,
        now: datetime,
        time_zone: str,
    ) -> CalendarEventIntent | None:
        """Detect whether user asks to create a Google Calendar event."""
        payload = {
            "model": self.model,
            "messages": [
                {
                    "role": "system",
                    "content": (
                        "Ты — парсер событий для Google Calendar. "
                        "Определи, хочет ли пользователь создать событие в календаре. "
                        "Верни ТОЛЬКО JSON, без Markdown, без пояснений. "
                        "Формат: "
                        '{"create_event": boolean, "summary": string|null, '
                        '"start_local": string|null, "end_local": string|null, '
                        '"description": string|null}. '
                        "start_local и end_local — ISO 8601 БЕЗ таймзоны, "
                        "например 2026-05-14T15:00:00. "
                        "Если время окончания не указано, считай длительность 1 час. "
                        "Для относительных дат (завтра, послезавтра, в понедельник) "
                        "используй текущую дату из сообщения ниже. "
                        "Если пользователь просит создать событие, встречу, "
                        "напоминание, звонок, совещание — это ВСЕГДА "
                        "create_event=true при наличии даты и времени. "
                        "Если нет намерения создать событие — create_event=false."
                    ),
                },
                {
                    "role": "user",
                    "content": (
                        f"Текущая дата и время: {now.isoformat()}\n"
                        f"Timezone: {time_zone}\n"
                        f"Текст пользователя: {text}"
                    ),
                },
            ],
        }
        headers = {
            "Authorization": f"Bearer {self.api_key}",
            "Content-Type": "application/json",
            "X-OpenRouter-Title": self.app_title,
        }

        async with httpx.AsyncClient(timeout=30) as client:
            response = await client.post(self.base_url, json=payload, headers=headers)

        if response.status_code >= 400:
            raise OpenRouterError(
                "OpenRouter calendar intent request failed with status "
                f"{response.status_code}."
            )

        content = self._extract_content(response.json())
        return self._parse_calendar_event_intent(content, time_zone)

    async def format_search_answer(
        self,
        query: str,
        search_response: SearchResponse,
    ) -> str:
        """Format Tavily search results into a concise Telegram answer."""
        tavily_json = json.dumps(
            search_response.raw_data,
            ensure_ascii=False,
            indent=2,
        )
        payload = {
            "model": self.model,
            "messages": [
                {
                    "role": "system",
                    "content": (
                        "Ты аналитик поиска. На основе JSON-ответа Tavily дай "
                        "краткий, структурированный ответ на русском в стиле "
                        "Telegram-чата. Используй только факты из Tavily. "
                        "Добавляй уместные эмодзи для разделов: кратко, детали, "
                        "источники. В конце обязательно добавь источники с URL. "
                        "Форматируй простым текстом без Markdown и HTML."
                    ),
                },
                {
                    "role": "user",
                    "content": (
                        f"Запрос пользователя: {query}\n\n"
                        f"Полный ответ Tavily:\n{tavily_json}"
                    ),
                },
            ],
        }
        headers = {
            "Authorization": f"Bearer {self.api_key}",
            "Content-Type": "application/json",
            "X-OpenRouter-Title": self.app_title,
        }

        async with httpx.AsyncClient(timeout=60) as client:
            response = await client.post(self.base_url, json=payload, headers=headers)

        if response.status_code >= 400:
            msg = (
                "OpenRouter search formatting failed with status "
                f"{response.status_code}."
            )
            raise OpenRouterError(msg)

        return self._extract_content(response.json())

    @staticmethod
    def _extract_content(data: dict[str, Any]) -> str:
        choices = data.get("choices")
        if not isinstance(choices, list) or not choices:
            raise OpenRouterError("OpenRouter response does not contain choices.")

        first_choice = choices[0]
        if not isinstance(first_choice, dict):
            raise OpenRouterError("OpenRouter choice has unexpected format.")

        message = first_choice.get("message")
        if not isinstance(message, dict):
            raise OpenRouterError("OpenRouter message has unexpected format.")

        content = message.get("content")
        if not isinstance(content, str) or not content.strip():
            raise OpenRouterError("OpenRouter response is empty.")

        return content.strip()

    @staticmethod
    def _extract_image_url(data: dict[str, Any]) -> str:
        choices = data.get("choices")
        if not isinstance(choices, list) or not choices:
            raise OpenRouterError("OpenRouter response does not contain choices.")

        first_choice = choices[0]
        if not isinstance(first_choice, dict):
            raise OpenRouterError("OpenRouter choice has unexpected format.")

        message = first_choice.get("message")
        if not isinstance(message, dict):
            raise OpenRouterError("OpenRouter message has unexpected format.")

        images = message.get("images")
        if not isinstance(images, list) or not images:
            raise OpenRouterError("OpenRouter response does not contain images.")

        first_image = images[0]
        if not isinstance(first_image, dict):
            raise OpenRouterError("OpenRouter image has unexpected format.")

        image_url = first_image.get("image_url")
        if not isinstance(image_url, dict):
            raise OpenRouterError("OpenRouter image URL has unexpected format.")

        url = image_url.get("url")
        if not isinstance(url, str) or not url.startswith("data:image/"):
            raise OpenRouterError("OpenRouter image URL is not a data URL.")

        return url

    @staticmethod
    def _decode_data_url(data_url: str) -> GeneratedImage:
        header, separator, payload = data_url.partition(",")
        if not separator or ";base64" not in header:
            raise OpenRouterError("OpenRouter image data URL has unexpected format.")

        media_type = header.removeprefix("data:").split(";", maxsplit=1)[0]
        extension = media_type.removeprefix("image/") or "png"

        try:
            content = base64.b64decode(payload, validate=True)
        except (binascii.Error, ValueError) as error:
            msg = "OpenRouter image data is not valid base64."
            raise OpenRouterError(msg) from error

        return GeneratedImage(content=content, extension=extension)

    @staticmethod
    def _parse_invoice_intent(content: str) -> InvoiceIntent | None:
        data = _extract_json_object(content, "invoice intent")

        if not isinstance(data, dict):
            raise OpenRouterError("OpenRouter invoice intent has unexpected format.")

        if data.get("create_invoice") is not True:
            return None

        amount = data.get("amount_usd")
        if not isinstance(amount, str | int | float):
            return None

        try:
            amount_usd = Decimal(str(amount).replace(",", "."))
        except InvalidOperation as error:
            msg = "OpenRouter invoice intent amount is not numeric."
            raise OpenRouterError(msg) from error

        if amount_usd <= 0:
            return None

        raw_assets = data.get("assets")
        if not isinstance(raw_assets, list):
            raw_assets = []

        supported_assets = {"USDT", "TON", "BTC"}
        assets = tuple(
            asset.upper()
            for asset in raw_assets
            if isinstance(asset, str) and asset.upper() in supported_assets
        )
        if not assets:
            assets = ("USDT", "TON", "BTC")

        description = data.get("description")
        if not isinstance(description, str) or not description.strip():
            description = f"Счет на ${amount_usd}"

        return InvoiceIntent(
            amount_usd=amount_usd,
            accepted_assets=assets,
            description=description.strip(),
        )

    @staticmethod
    def _parse_calendar_event_intent(
        content: str,
        time_zone: str,
    ) -> CalendarEventIntent | None:
        data = _extract_json_object(content, "calendar event intent")

        if data.get("create_event") is not True:
            return None

        summary = data.get("summary")
        start_local = data.get("start_local")
        end_local = data.get("end_local")
        if not isinstance(summary, str) or not summary.strip():
            return None
        if not isinstance(start_local, str):
            return None

        try:
            zone = ZoneInfo(time_zone)
            start_at = OpenRouterClient._parse_naive_datetime(start_local, zone)
            if isinstance(end_local, str) and end_local.strip():
                end_at = OpenRouterClient._parse_naive_datetime(end_local, zone)
            else:
                end_at = start_at + timedelta(hours=1)
        except ValueError as error:
            msg = "OpenRouter calendar event datetime is not valid ISO 8601."
            raise OpenRouterError(msg) from error

        if end_at <= start_at:
            return None

        description = data.get("description")
        if not isinstance(description, str) or not description.strip():
            description = None

        return CalendarEventIntent(
            summary=summary.strip(),
            start_at=start_at,
            end_at=end_at,
            description=description.strip() if description else None,
        )

    @staticmethod
    def _parse_naive_datetime(
        raw: str,
        zone: ZoneInfo,
    ) -> datetime:
        """Strip any trailing timezone info and attach the configured zone."""
        normalized = raw.strip()
        # Remove trailing Z or offset (+HH:MM or -HH:MM)
        for suffix in ("Z", "+00:00", "+0000"):
            if normalized.endswith(suffix):
                normalized = normalized[: -len(suffix)]
                break
        else:
            # Try removing any ±HH:MM or ±HHMM offset
            match = re.search(r"[+-]\d{2}:?\d{2}$", normalized)
            if match:
                normalized = normalized[: match.start()]

        parsed = datetime.fromisoformat(normalized)
        if parsed.tzinfo is not None:
            # If fromisoformat still produced an aware datetime,
            # convert to target zone first, then make naive
            parsed = parsed.astimezone(zone).replace(tzinfo=None)
        return parsed.replace(tzinfo=zone)


def _extract_json_object(content: str, context: str) -> dict[str, Any]:
    json_start = content.find("{")
    json_end = content.rfind("}")
    if json_start == -1 or json_end == -1:
        raise OpenRouterError(f"OpenRouter {context} response is not JSON.")

    try:
        data = json.loads(content[json_start : json_end + 1])
    except json.JSONDecodeError as error:
        msg = f"OpenRouter {context} response is not valid JSON."
        raise OpenRouterError(msg) from error

    if not isinstance(data, dict):
        raise OpenRouterError(f"OpenRouter {context} has unexpected format.")

    return data
